name: harvest
version: 2.0.13
author: Lars Tackmann <lars@solvr.io>
description: Messagebus, CQRS framework and eventstore for Dart with multiple backends
homepage: https://github.com/ltackmann/harvest
environment:
  sdk: ">=2.8.0"
dependencies:
  dart_json_mapper:
  logger:
  uuid: "^2.2.2"
dev_dependencies:
  build_runner: "^1.0.0"
  test: any
